# Generated by Django 3.0 on 2020-11-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customers',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
